name: Non-update Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: base

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK 💻
        uses: android-actions/setup-android@v3

      - name: Pull upstream 🌏
        run: |
          git remote add upstream https://github.com/KotatsuApp/Kotatsu.git
          git fetch upstream devel
          git reset --hard upstream/devel

      - name: Grant permissions 💻
        run: chmod a+x gradlew

      - name: Generate build number 📆
        id: tagger
        run: |
          echo "new_tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "formatted_date=$(date +'%Y/%m/%d')" >> $GITHUB_OUTPUT

      - name: Fixing for Nightly APK 🔧
        run: |
          sed -i '/<SwitchPreferenceCompat/,/android:title="@string\/allow_unstable_updates"/d' app/src/main/res/xml/pref_about.xml

      - name: Building Nightly APK 💻
        run: >-
          ./gradlew assembleNightly
          -DparsersVersionOverride=$(curl -s https://api.github.com/repos/kotatsuapp/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
        continue-on-error: true

      - name: Building Nightly APK (Attempt 2) 💻
        if: failure()
        run: >-
          ./gradlew assembleNightly
          -DparsersVersionOverride=$(curl -s https://api.github.com/repos/kotatsuapp/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)

      - name: Packaging Nightly APK 💻
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/nightly
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Prepare to Upload 🌏
        run: |
          mv ${{steps.sign_app.outputs.signedFile}} app/build/outputs/apk/nightly/release.apk
          echo "SIGNED_APK=app/build/outputs/apk/nightly/release.apk" >> $GITHUB_ENV
          echo "MAPPING_FILE=app/build/outputs/mapping/nightly/mapping.txt" >> $GITHUB_ENV

      - name: Get latest changes 📑
        id: changelog
        run: |
          curl -o commit.py -L https://raw.githubusercontent.com/KotatsuApp/Kotatsu-nightly/nightly/.github/assets/commit.py
          python3 commit.py
          
          CHANGELOG=$(cat commits.txt)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create new GH Release + Uploading 🌏
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ steps.tagger.outputs.new_tag }}
          name: "Nightly Build ${{ steps.tagger.outputs.new_tag }}"
          body: |
            Automated nightly build generated on ${{ steps.tagger.outputs.formatted_date }}

            ${{ steps.changelog.outputs.content }}
          files: |
            ${{ env.SIGNED_APK }}
            ${{ env.MAPPING_FILE }}
          prerelease: false

  update:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: nightly
          fetch-depth: 0

      - name: Update Build Number 📆
        run: |
          VERSION_NUMBER="${{ needs.build.outputs.new_tag }}"
          COUNTER_LINKS=""          
          for (( i=0; i<${#VERSION_NUMBER}; i++ )); do
            DIGIT="${VERSION_NUMBER:$i:1}"
            COUNTER_LINKS+="[![Download](https://rule34.xxx/counter/$DIGIT.gif)](https://github.com/KotatsuApp/kotatsu-nightly/releases/latest) "
          done
          sed -i "/### <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/> Download <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/>/,/div>/c\### <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/> Download <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/>\n\n${COUNTER_LINKS}\n\n<div align=\"left\">\n\n* Nightly build can be downloaded from the [GitHub Releases](https://github.com/KotatsuApp/Kotatsu-Nightly/releases). Application has a built-in self-updating feature.\n* If you want to download a stable Kotatsu release please refer to the [main Kotatsu repository](https://github.com/KotatsuApp/Kotatsu?tab=readme-ov-file#download).\n\n</div>" README.md

      - name: Update Docs + Commit 🌏
        run: |
          git config --local user.email "bot@kotatsu.app"
          git config --local user.name "kotatsu-bot"
          if [[ -n $(git status -s) ]]; then
            git add README.md
            git commit -m "Bump build number to ${{ needs.build.outputs.new_tag }}"
            git push origin nightly
          else
            echo "No changes to push!"
          fi