name: Non-update Builds (Legacy)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: base

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK 💻
        uses: android-actions/setup-android@v3

      - name: Pull upstream 🌏
        run: |
          git remote add upstream https://github.com/KotatsuApp/Kotatsu-Nightly.git
          git fetch upstream legacy
          git reset --hard upstream/legacy

      - name: Grant permissions 💻
        run: chmod a+x gradlew

      - name: Generate build number 📆
        id: tagger
        run: |
          echo "new_tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "formatted_date=$(date +'%Y/%m/%d')" >> $GITHUB_OUTPUT

      - name: Building new APK 💻
        run: >-
          ./gradlew assembleNightly
          -DparsersVersionOverride=$(curl -s https://api.github.com/repos/draggonx943/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)

      - name: Packaging new APK 💻
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/nightly
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Prepare to Upload 🌏
        run: |
          mv ${{steps.sign_app.outputs.signedFile}} app/build/outputs/apk/nightly/release.apk
          echo "SIGNED_APK=app/build/outputs/apk/nightly/release.apk" >> $GITHUB_ENV

      - name: Get latest changes 📑
        id: changelog
        run: |
          CHANGELOG=$(cat CHANGELOG.txt)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create new GH Release + Uploading 🌏
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ steps.tagger.outputs.new_tag }}-legacy
          name: "Nightly Build ${{ steps.tagger.outputs.new_tag }} (Legacy)"
          body: |
            Automated Legacy nightly build generated on ${{ steps.tagger.outputs.formatted_date }}

            ${{ steps.changelog.outputs.content }}
          files: ${{ env.SIGNED_APK }}
          prerelease: true
